# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/parallels/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
#
alias open=xdg-open
function ss() { xdg-open "https://ddg.gg/$*" ; }
alias ll='ls -l'
alias wh=which
alias e=echo

